# Generated by Django 5.2.10 on 2026-08-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0031_encounterpokemondetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounterslot",
            name="rarity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
