# Generated by Django 5.2.10 on 2026-08-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_v2", "0032_pokemonformcondition_base_form"),
    ]

    operations = [
        migrations.RenameField(
            model_name="encounterpokemondetail",
            old_name="is_alpha",
            new_name="always_alpha",
        ),
        migrations.AddField(
            model_name="encounterpokemondetail",
            name="alpha_max_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="encounterpokemondetail",
            name="alpha_min_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="encounterslot",
            name="rarity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
